### ISSUE TITLE
Isomorphic / SSR Issue

### ISSUE THREAD

**Issue by jrodl3r** [peerigon/modernizr-loader#15]
Modernizr throws: `window is not defined` on server (React/SSR)

any ideas on how to work around that in webpack/React/SSR environment?

**Comment by jrodl3r** [comment]
...

**Comment by flootr** [comment]
The error is correct, you won't be able to use Modernizr on the server side as you don't have any DOM to access and therefore no `window` object.

You could define a `window` object with the [`webpack.DefinePlugin`](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) to work around this issue and create a fake `window` object. This is one approach, but there may be others which may fit better for your use case.

**Comment by jrodl3r** [comment]
got this far:

```
new webpack.DefinePlugin({
  'window': JSON.stringify('object'),
  'document': JSON.stringify('object'),
  'navigator': JSON.stringify('object')
}),
```

then it just becomes an endless stream of errors on missing methods, etc.

**Comment by flootr** [comment]
Maybe try to only require Modernizr if you're in a DOM environment? Sorry, but I am not able to get that deep into your project for time reasons.

**Comment by jrodl3r** [comment]
@flootr Thx! that helped me get it working (and disabled) for the appropriate webpack modes
(__ DEVCLIENT __ / __ DEVSERVER __ / __ PRODCLIENT __)

**Comment by rlindskog** [comment]
@jrodl3r @flootr I made a modernizr server implementation for express.  Check it out if you're interested. [modernizr-server](http://github.com/rlindskog/modernizr-server).

Take a look at this issue too.  [Issue #27](https://github.com/peerigon/modernizr-loader/issues/27)
