### ISSUE TITLE
Installation process clarification

### ISSUE THREAD

**Issue by tikhonbelousko** [peerigon/modernizr-loader#16]
Hi! 

Small clarification. Do users really need to do `npm install --save modernizr-loader`, wouldn't it be better to use `--save-dev` flag, since it is a common practice to put loaders to devDependecies. 

What do you think about that? 💭

**Comment by flootr** [comment]
True! Would you mind open a PR on that?

**Comment by tikhonbelousko** [comment]
On it 👍
