### ISSUE TITLE
modernizr package is required

### ISSUE THREAD

**Issue by jmarceli** [peerigon/modernizr-loader#19]
It looks like proper README installation command should be:

```
$ npm install --save-dev modernizr modernizr-loader
```

As the `modernizr` is required to generate final bundle or am I missing something?

**Comment by flootr** [comment]
No, you are correct. `modernizr` is a peerDependency and won't get installed since `npm@3`. You'd likely want to install `modernizr`, too. Would you mind opening a PR on that @jmarceli?

**Comment by flootr** [comment]
#20
