### ISSUE TITLE
"You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by gmli-eu** [peerigon/modernizr-loader#29]
Hi everyone,

I've spent the last couple of hours trying to add Modernizr to my webpack 2 setup but I wasn't able to solve this error:
`Module not found: Error: Can't resolve 'modernizr' in .../Webpack2Setup/src/js/main.js`

**.../Webpack2Setup/package.json**
```
...
"devDependencies": {
  ...
  "modernizr": "^3.3.1",
  "modernizr-loader": "^1.0.1",
  ...
},
...
```

**.../Webpack2Setup/webpack.config.js**
```
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HTMLWebpackPlugin = require('html-webpack-plugin');

const PRODUCTION = process.env.NODE_ENV === 'production';
const DEVELOPMENT = process.env.NODE_ENV === 'development';

var entry = PRODUCTION
  ? ['./src/js/main.js']
  : [
      './src/js/main.js',
      'webpack/hot/dev-server',
      'webpack-dev-server/client?http://localhost:8080'
    ];

var plugins = PRODUCTION
  ? [
      new webpack.optimize.UglifyJsPlugin(),
      new ExtractTextPlugin('style-[contenthash:10].min.css'),
      new HTMLWebpackPlugin({
        template: 'index-template.html'
      })
    ]
  : [
      new webpack.HotModuleReplacementPlugin()
    ];

plugins.push(
  new webpack.DefinePlugin({
    PRODUCTION: JSON.stringify(PRODUCTION),
    DEVELOPMENT: JSON.stringify(DEVELOPMENT)
  })
);

const scssIdentifier = PRODUCTION ? '[hash:base24:10]' : '[path][name]---[local]';

// Loaders are read from right to left
const scssLoader = PRODUCTION
  ? ExtractTextPlugin.extract({
      loader: ['css-loader?minimize&importLoaders=1', 'postcss-loader', 'sass-loader?localIdentName=' + scssIdentifier]
    })
  : ['style-loader', 'css-loader?importLoaders=1', 'postcss-loader', 'sass-loader?localIdentName=' + scssIdentifier];

module.exports = {
  externals: {
    'jquery': 'jQuery'
  },
  devtool: DEVELOPMENT ? 'source-map' : false,
  entry: entry,
  plugins: plugins,
  module: {
    rules: [
      {
        test: /\.js$/,
        enforce: "pre",
        loader: "eslint-loader"
      },
      {
        test: /\.modernizrrc.js$/,
        loader: "modernizr"
      },
      {
        test: /\.js$/,
        use: ['babel-loader'],
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: ['url-loader?limit=10000&name=images/[hash:12].[ext]'],
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        use: scssLoader,
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    alias: {
      modernizr$: __dirname + "./.modernizrrc"
    }
  },
  output: {
    path: __dirname + '/dist',
    publicPath: PRODUCTION ? '/' : '/dist/',
    filename: PRODUCTION ? 'bundle.[hash:12].min.js' : 'bundle.js'
  }
};
```

**.../Webpack2Setup/.modernizrrc**
```
{
  "minify": false,
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/css/flexbox",
    "test/es6/promises",
    "test/serviceworker"
  ]
}
```

**.../Webpack2Setup/src/js/main.js**
```
...
import Modernizr from 'modernizr';
...
```

There's something missing? If you need to take a look at the complete repo, you can find it [here](https://github.com/MADPT/Webpack2Setup) (without Modernizr).

Thank you in advance

**Comment by gmli-eu** [comment]
I had a typo in the webpack.config.js `resolve` but it didn't fixed the issue.

**.../Webpack2Setup/webpack.config.js (FIXED)**
```
...
resolve: {
  alias: {
    modernizr$: __dirname + "/.modernizrrc"
  }
},
...
```

**New error**
```
ERROR in ./.modernizrrc
Module parse failed: .../Webpack2Setup/.modernizrrc Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
| {
|   "minify": false,
|   "options": [
|     "setClasses"
```

**Comment by flootr** [comment]
Hey! This might be due to your loader configuration. You are expecting a `/\.modernizrrc.js$/`, but you are aliasing `modernizr` to `.modernizrrc`.

**Comment by gmli-eu** [comment]
I don't guess that's the reason because, if I remove everything inside `.modernizrrc` (just leave {} ), webpack runs perfectly

**Comment by flootr** [comment]
> I don't guess that's the reason because, if I remove everything inside .modernizrrc (just leave {} ), webpack runs perfectly

Nevertheless, your loader configuration for Modernizr would not apply to the provided file because the regex does not match. The error message

> Unexpected token (2:10)
> You may need an appropriate loader to handle this file type.

is, at least in my experience, almost everytime caused by a _"falsy"_ loader configuration. So there might be an issue there which is not caused by the modernizr-loader itself. 

I cloned your repo and it happens to be that webpack is not recognizing your `.modernizrrc` as a `json` file. If you pass in the [`json-loader`](https://github.com/webpack-contrib/json-loader) into your configuration like so

```
{
  test: /\.modernizrrc/,
  loader: 'modernizr-loader!json-loader'
},
```

it should run successfully.

However, I thought that `webpack@2` is capable of reading `json` files. Maybe @jhnns has some input here. It might be due to the `alias`.

**Comment by gmli-eu** [comment]
@flootr you're right, I just needed to update the `loader: 'modernizr-loader!json-loader'`

That's a good question because I read somewhere that I didn't need `json-loader` with webpack 2. Probably I don't need to install it (I don't have it on my package.json) but I have to pass it into my configuration.

Thank you for your help 😄

**Comment by jhnns** [comment]
Webpack 2 will only apply the json-loader by default if the file extension is `.json`

**Comment by giannif** [comment]
@jhnns can't get this going with `Webpack 2`. Was working with `Webpack 1` just fine.

If I rename `.modernizrrc` to `.modernizrrc.json`, the json is parsed, but then 

```javascript
import Modernizr from 'modernizr'
```

Imports the json, probably because I have this as an alias: 
```javascript
alias: {
  modernizr$: path.resolve(__dirname, "./.modernizrrc.json"),
``` 

And I feel like that's where things go wrong...

Separately, if I don't append `.json` to `.modernizrrc`, I can't get the json-loader to kick in:
In that scenario, my rules look like: 
```javascript
{
    test: /\.modernizrrc.js$/,
    use: ["modernizr-loader"]
}, {
    test: /\.modernizrrc(\.json)?$/,
    use: ["modernizr-loader", "json-loader"]
}
```

Wondering what approach I should take...

Any help would be appreciated, I've tried a lot of things to no avail.
