### ISSUE TITLE
The modernizr-loader does not work with karma-webpack

### ISSUE THREAD

**Issue by tonytangau** [peerigon/modernizr-loader#33]
When try to use karma-webpack to run jasmine tests, with the same loaders as dev/prod, it throws error
```
ERROR in ./.modernizrrc
Module parse failed: C:\PathToRoot\.modernizrrc Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
```
The other tests (for modules do not require modernizr) runs fine.

**Comment by flootr** [comment]
Could you please provide me with your webpack config? The given error message indicates there may be a misconfiguration with the loaders.

**Comment by tonytangau** [comment]
There was a mistake in the config, thanks for the reply, I will close this issue.

**Comment by ghost** [comment]
WHAT WAS THE MISTAKE?!?!?!
