### ISSUE TITLE
Error when parsing modernizrrc

### ISSUE THREAD

**Issue by ghost** [peerigon/modernizr-loader#38]
When I followed your readme I received following error:

```
ERROR in ./.modernizrrc
Module build failed: ...\app\.modernizrrc:2
  "minify": true,
          ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.exec (...\app\node_modules\webpack\lib\NormalModule.js:126:12)
    at Object.module.exports (...\app\node_modules\modernizr-loader\index.js:24:26)
```

My .modernizrrc :
```
{
  "minify": true,
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "serviceworker",
    "svg",
    "picture",
    "promises"
  ]
}
```
And packages used
```
"modernizr": "3.5.0",
"modernizr-loader": "1.0.1",
"webpack": "2.5.0",
```

**Comment by flootr** [comment]
@hsbc-maciejpanecki could you provide me with your webpack config? I'm especially interested in the part with the loaders.

**Comment by ghost** [comment]
I solved it with a use of json-loader:
```
{
        test: /\.modernizrrc(\.json)$/,
        use: [
          { loader: 'modernizr-loader' },
          { loader: 'json-loader' }
        ]
      }
```
that was suggested in this PR: https://github.com/peerigon/modernizr-loader/pull/37

And I have this setting in my resolve:
```
resolve: {
    extensions: ['.ts', '.js'],
    alias: {
      modernizr$: path.resolve(__dirname, '.modernizrrc')
    }
  }
```

**Comment by ghost** [comment]
What I do not understand is what is a purpose of this code:
```
{
        test: /\.modernizrrc.js$/,
        loader: "modernizr"
      },
```
What is it purpose? Now I just got ```.modernizrrc.json``` and it works fine.

**Comment by flootr** [comment]
> purpose of this code

You don't have to use `json` format for your `modernizrrc`. You are allowed to use a javascript file instead, then you won't need the `json-loader`.

**Comment by ghost** [comment]
So it is one OR the other depending on your choosing. Nice. You should definitely update readme file.
