### ISSUE TITLE
json-loader is not required for webpack v2 and above

### ISSUE THREAD

**Issue by msholty-fd** [peerigon/modernizr-loader#40]
The documentation for this loader instructs you to install `json-loader`, but for users on webpack 2 and above, it is not required. This is one of the first lines in json-loader:

> ⚠️ Since webpack >= v2.0.0, importing of JSON files will work by default. You might still want to use this if you use a custom file extension. See the v1.0.0 -> v2.0.0 Migration Guide for more information

**Comment by jhnns** [comment]
Thanks for the hint, but the json-loader is indeed required. Webpack 2 applies the json-loader by default *if no other loader is configured for that file type*. If you need any other loader (like the modernizr-loader), you need to configure the json-loader explicitly.
