### ISSUE TITLE
Errors with Webpack build

### ISSUE THREAD

**Issue by dcalhoun** [peerigon/modernizr-loader#5]
I'm having difficulties getting modernizr-loader setup. I followed the README, but unfortunately hit a lot of errors anytime I attempt to `import Modernizr from 'modernizr'`. Any thoughts as to what is going on here? Thanks!
### Errors

_[Full list of errors](https://gist.github.com/dcalhoun/04d48160bc14610c6377c190f86e8798)_

```
ERROR in ./~/modernizr/lib/build.js
Module not found: Error: Cannot resolve module 'generate' in /Users/username/Sites/web/gn-join/node_modules/modernizr/lib
 @ ./~/modernizr/lib/build.js 151:2-72

[...]
```
### Config

``` javascript
// webpack.config.js
var path = require('path')

module.exports = {
  entry: path.join(__dirname,'./src/index.js'),

  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: 'assets'
  },

  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel' },
      { test: /\.json$/, loader: 'json' },
      { test: /\.modernizrrc$/, loader: 'modernizr'}
    ]
  },

  resolve: {
    modernizr$: path.resolve(__dirname, '.modernizrrc')
  }
}
```

``` bash
# .modernizrrc
{
  "minify": true,
  "options": [
    "setClasses"
  ],
  "feature-detects": [
    "test/touchevents"
  ]
}
```
### Peer Dependency Versions
- `webpack@1.12.14`
- `modernizr@3.3.1`

**Comment by flootr** [comment]
You might have an error in your webpack config. Please provide `modernizr` as an `alias` in the `resolve` part. That's missing in your configuration:

``` js
resolve: {
    alias: {
      modernizr$: path.resolve(__dirname, "path/to/.modernizrrc")
    }
  }
```

**Comment by dcalhoun** [comment]
@flootr yep, I was afraid it was a simple mistake. Sorry for wasting your time. Thank you for the assistance!

**Comment by vivekgs2007** [comment]
Got the same Issue.

Changed as mentioned by @flootr but still no Luck;.


Webpack: v2.1.0-beta.20
