### ISSUE TITLE
readme fix

### ISSUE THREAD

**Issue by Brototype** [peerigon/modernizr-loader#6]
shouldn't it be `require("!modernizr!/.modernizrrc")`(with an **!**) instead of `require("!modernizr./.modernizrrc")`(with a **.**)?

**Comment by danilobuerger** [comment]
should be `require("!modernizr!./.modernizrrc")`

**Comment by flootr** [comment]
Thanks 👍 c597f5da205708d89ff59f3f6d37c7cc95816458
