### ISSUE TITLE
cacheable

### ISSUE THREAD

**Issue by danilobuerger** [peerigon/modernizr-loader#7]
Is there a reason this loader does not opt in to being cacheable?

**Comment by jhnns** [comment]
Nope. You're right. We should add a [cachable flag](https://github.com/peerigon/markdown-loader/blob/1454d5152a5ccb172213faadfe034d1bb75e1bd2/index.js#L25) @flootr

**Comment by jhnns** [comment]
The cacheable flag tells webpack that ~~the loader has no side-effects.~~ when the input hasn't changed, the previous output can be reused.

EDIT: The loader may have side-effects.

**Comment by danilobuerger** [comment]
What side-effects could it have?

**Comment by jhnns** [comment]
From a technical point of view, calling `cacheable()` itself is a side-effect

**Comment by danilobuerger** [comment]
> The cacheable flag tells webpack that the loader has no side-effects.

Actually the webpack docs just states it must be deterministic:

> A cacheable loader must have a deterministic result, when inputs and dependencies haven’t changed.

So my question should have rather been: is there anything that doesn't make it deterministic?

**Comment by jhnns** [comment]
Yes, deterministic is the correct word (in contrast to "without side-effect"). 

> is there anything that doesn't make it deterministic?

Nope

**Comment by danilobuerger** [comment]
Since this is assigned to @flootr i guess you guys don't need a PR for it?

**Comment by flootr** [comment]
> Since this is assigned to @flootr i guess you guys don't need a PR for it?

If you want to, go for it @danilobuerger 👍  Would really appreciate it.
