### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by danilobuerger** [peerigon/modernizr-loader#9]
Where are the tests that i can run with `npm test` (according to the README) ?

**Comment by flootr** [comment]
There are no tests. I started to write tests but haven't pushed, yet.

**Comment by danilobuerger** [comment]
Wouldn't it make sense to remove that part from README.md then? Also from package.json as that creates an infinite loop calling `npm test`.

**Comment by flootr** [comment]
I agree with you. I'll push the tests as soon as I'm ready with them. Hopefully very soon ^^

Done via bd2283e33ed4caea7e373e202bfbafabe6ba2f04
